
FROM ubuntu:latest
RUN apt-get update && apt-get install -y\
	g++ \
    valgrind \
    build-essential \
    gdb \
	vim
RUN apt-get install -y emacs
RUN apt-get install -y man-db
RUN apt-get install -y curl
RUN apt-get install -y git
RUN apt-get install -y git
RUN apt-get install -y time

